### ISSUE TITLE
DetectAUM branch crashes at end of every game

### ISSUE THREAD

**Issue by Cyber-Crud** [BitCrackers/AmongUsMenu#157]
I downloaded and compiled the DetectAUM branch and most of other bugs seem fixed, like the skins disappearing.  However the game crashes at the conclusion of every match.  Once the last Imp is ejected, the game crashes at the ejection screen.  This is reproducible every time.  I have not played as imp yet to see how it behaves.

Also, the cheat detection in the console I think is incorrectly showing imps using teleportation when they are not.

**Comment by OsOmE1** [comment]
I still haven't found the cause of the first issue.
Second issue should be solved soon

**Comment by manianac** [comment]
I have played quite a few games on this branch now, try pulling the latest commits.

**Comment by Cyber-Crud** [comment]
Still crashes at the end of the game.  And I just now had a crash in the
middle of the game while I was crew with one imp remaining.  Maybe the last
imp left and it caused the same game crash?

Here are the 2 warnings that I get on compiling the version that you
updated in the last 2 hours:

d:\vs2019\amongusmenu-detectaum\hooks\directx.cpp(175): warning C4834:
discarding return value of function with 'nodiscard' attribute
d:\vs2019\amongusmenu-detectaum\hooks\innernetclient.cpp(110): warning
C4244: 'initializing': conversion from 'float' to 'int32_t', possible loss
of data

**Comment by Cyber-Crud** [comment]
So I converted the code to v142 and recompiled.  The crashing is gone, but
it still black screens at the end of the game rather than going to the
victory/defeat screen.

I might run it without any cheats enabled to see if I can narrow down what
is causing the issue.
